- src/App.tsx
- src/components/Card/TransactionCard.tsx
- src/components/Footer/index.tsx
- src/components/Header/index.tsx
- src/components/Label/index.tsx
- src/components/Page/index.tsx
- src/components/Search/index.tsx
- src/components/Transaction/styled.tsx
- src/index.css
- src/pages/404/index.tsx
- src/pages/Address/index.tsx
- src/pages/Address/styled.tsx
- src/pages/BlockDetail/index.tsx
- src/pages/BlockDetail/styled.tsx
- src/pages/BlockList/index.tsx
- src/pages/BlockList/styled.tsx
- src/pages/Home/index.tsx
- src/pages/Home/styled.tsx
- src/pages/SearchFail/index.tsx
- src/pages/Transaction/index.tsx
- src/pages/Transaction/styled.tsx
- src/routes/index.tsx
* Remove resize event listener
* Replace innerWidth with @media
* Replace route component with render
> fix: fix http request and page render error

- src/components/Card/BlockCard.tsx
- src/components/Card/CellCard.tsx
- src/components/Card/TransactionCard.tsx
- src/components/Header/index.tsx
- src/components/Label/index.tsx
- src/components/Search/index.tsx
- src/pages/Address/styled.tsx
- src/pages/BlockDetail/styled.tsx
- src/pages/Home/index.tsx
- src/pages/Home/styled.tsx
* Set item name and highlight value to bold
* Adjust page element margin 
* Add separator to hash rate
> fix: fix ui bugs of pages

- src/App.tsx
- src/components/Card/TransactionCard.tsx
- src/http/fetcher.ts
- src/pages/BlockDetail/index.tsx
- src/pages/BlockList/index.tsx
* Refactor block list useEffect dependence
* Use http error code to avoid show error sheet
* Fix some undefined bugs
> Refactor block list use effect

- src/components/Card/BlockCard.tsx
- src/components/Label/index.tsx
- src/components/Sheet/index.tsx
- src/components/Toast/index.tsx
- src/pages/Address/index.tsx
- src/pages/BlockDetail/index.tsx
* Set miner font to normal instead of monospace
* Update miner hash more shorter
* Fix toast position error
> fix ui bugs

- src/pages/Maintain/index.tsx
* Add maintain page when server is deploying and not ready.
* Add fetch genesis block request, so when server is ok, user can visit home page through refreshing again.
> feat: add http check to maintain page

- src/components/Search/index.tsx
This PR solved the question that search keyword can't clean when searching success .
And it needs merge to release branch to promise testing is normal.
> [ᚬrelease] Refactor search component

- src/utils/util.ts
> fix: Issue object may be null

- src/utils/util.ts
> [ᚬrelease] fix: Parse capacity number

- src/pages/Home/index.tsx
- src/pages/Home/styled.tsx
* Add `flex-wrap` to home statistics items
> [ᚬrelease] chore: adjust statistics item layout on small pc pixel

- src/pages/Address/index.tsx
- src/pages/BlockDetail/index.tsx
- src/pages/BlockList/index.tsx
- src/utils/string.ts
- tests/string.test.ts
* Refactor parsePageNumber method
* Refactor page and size logic of block list / block detail / address
> Refactor page and size logic of pagination

- src/components/Header/index.tsx
- src/components/Table/index.tsx
- src/index.css
- src/pages/Address/styled.tsx
- src/pages/BlockDetail/styled.tsx
- src/pages/Transaction/styled.tsx
According to production, I changed font weight to 450
> chore: update font weight to 450

- src/App.tsx
- src/components/Sheet/index.tsx
- src/contexts/App.tsx
- src/locales/en.json
- src/pages/Maintain/index.tsx
- src/providers/index.tsx
- src/routes/index.tsx
- src/utils/const.ts
- src/utils/hooks.ts
* Move App hooks to `utils/hooks`
* Fix sheet ui bug
> [ᚬrelease] Refactor app hooks 

- src/service/app/statisticsChart.ts
Check hash rate array and difficulty array whether are empty before `foreach` operation.
> [ᚬrelease] refactor: update statistic chart data handle logic

- src/components/Footer/styled.tsx
- src/components/Header/styled.tsx
- src/components/Search/styled.tsx
- src/pages/SearchFail/index.tsx
* Adjust header search bar position
* Adjust footer item width
* Adjust search icon and empty message font size
> [ᚬrelease] Adjust header / search / footer css

- src/pages/BlockList/index.tsx
- src/pages/Home/index.tsx
- src/service/app/block.ts
- src/service/app/statistics.ts
Move block and statistic cache data of home and block list pages to service module
> Refactor home and block list page cache data

- src/components/Card/AddressHashCard.tsx
- src/components/Search/styled.tsx
* Add title as useEffect dependence to reader again when title change
* Update search input padding right to adapt mobile
> [ᚬrelease] fix: fix lock hash width bug

- src/components/Loading/SmallLoading.tsx
- src/pages/Transaction/TransactionCellList/index.tsx
- src/pages/Transaction/TransactionCellList/styled.tsx
- src/pages/Transaction/TransactionCellScript/index.tsx
- src/pages/Transaction/TransactionComp.tsx
* Show loading animation when cell list component scroll to bottom
* Show loading animation for fetching transaction cell data
> feat: show loading animation when cell list component scroll to bottom

- src/components/TransactionItem/TransactionConfirmation/index.tsx
- src/components/TransactionItem/TransactionItemCell/index.tsx
- src/components/TransactionItem/TransactionItemCellList/index.tsx
- src/components/TransactionItem/TransactionReward/index.tsx
- src/components/TransactionItem/index.tsx
- src/components/TransactionItem/styled.tsx
- src/contexts/states/transaction.ts
- src/pages/Transaction/TransactionCell/index.tsx
- src/pages/Transaction/TransactionCellList/index.tsx
- src/pages/Transaction/TransactionCellScript/index.tsx
- src/types/App/index.d.ts
* Rename InputOutput to Cell
* Add transaction income
* Update transaction view all condition
> feat: update address transaction list

- src/App.tsx
- src/components/Footer/index.tsx
- src/components/Footer/styled.tsx
- src/components/Pagination/styled.tsx
- src/components/Table/index.tsx
- src/components/Toast/index.tsx
- src/components/TransactionItem/TransactionConfirmation/styled.tsx
- src/components/TransactionItem/TransactionItemCell/styled.tsx
- src/components/TransactionItem/TransactionItemCellList/styled.tsx
- src/components/TransactionItem/styled.tsx
- src/contexts/providers/hook.ts
- src/contexts/providers/reducer.ts
- src/contexts/states/app.ts
- src/pages/Address/styled.tsx
- src/pages/BlockDetail/styled.tsx
- src/pages/BlockList/styled.tsx
- src/pages/Home/styled.tsx
- src/pages/Transaction/TransactionCell/styled.tsx
- src/pages/Transaction/TransactionCellScript/styled.tsx
- src/pages/Transaction/styled.tsx
- src/types/App/index.d.ts
- src/utils/const.ts
> feat: support mainnet and testnet theme colors

- src/components/Card/HashCard.tsx
- src/components/Error/index.tsx
- src/components/Header/index.tsx
- src/components/Search/DaoSearch.tsx
- src/contexts/providers/reducer.ts
- src/contexts/states/index.ts
- src/pages/Address/AddressComp.tsx
- src/pages/Address/styled.tsx
- src/pages/BlockDetail/BlockComp.tsx
- src/pages/BlockDetail/styled.tsx
- src/pages/BlockList/index.tsx
- src/pages/Home/index.tsx
- src/pages/NervosDao/DaoTransactions.tsx
- src/pages/NervosDao/DepositorRank.tsx
- src/pages/NervosDao/styled.tsx
- src/pages/StatisticsChart/index.tsx
- src/service/app/statisticsChart.ts
- src/types/App/index.d.ts
- Fix some spelling mistakes
- Rename datas to dataList or data
- Set array default value to []
> refactor: rename datas to dataList and refactor array default value

- package.json
- src/components/Search/DaoSearch.tsx
- src/pages/NervosDao/DaoTransactions.tsx
- src/pages/NervosDao/DepositorRank.tsx
- src/pages/NervosDao/index.tsx
- src/pages/NervosDao/styled.tsx
- src/service/app/nervosDao.ts
- src/service/http/fetcher.ts
- src/types/App/index.d.ts
- yarn.lock
- Fix nervos dao transactions pagination bug
- Adapt nervos dao rank for mobile
- Update nervos dao related css style
> Fix some nervos dao bugs

- src/pages/NervosDao/DepositorRank.tsx
- src/pages/NervosDao/index.tsx
- Set tab to nervos dao url
- Update nervos dao rank capacity font family
> [ᚬmaster] Set tab to nervos dao url

- src/locales/en.json
- src/locales/zh.json
- src/pages/StatisticsChart/index.tsx
- src/service/app/statisticsChart.ts
- Update x-axis scale more bigger
- Remove first 4 epoch data for Difficulty/Hash Rate chart
> [ᚬmaster] Update chart axis scale

- src/pages/NervosDao/index.tsx
- src/pages/NervosDao/styled.tsx
Update nervos dao page title from [ nervos dao + type hash ] to [ nervos dao ]
> [ᚬmaster] Update nervos dao page title

- src/pages/StatisticsChart/index.tsx
- src/utils/chart.ts
- tests/chart.test.ts
- tests/date.test.ts
- tests/number.test.ts
- tests/string.test.ts
- tests/uri.test.ts
- tests/util.test.ts
- Update chart x-axis 
- Move chart function to util/chart
- Format test files
> [ᚬmaster] Update chart axis

- src/components/Footer/styled.tsx
- src/components/Header/styled.tsx
- src/pages/StatisticsChart/CellCount.tsx
- Update cell count chart axis
- Update mobile header and footer css
> [ᚬmaster] Update cell count chart and mobile css

- src/locales/en.json
- src/locales/zh.json
- src/pages/StatisticsChart/AddressBalanceRank.tsx
- Add log and `B` to balance ranking axis
> [ᚬmaster] Update charts axis

- src/locales/en.json
- src/pages/Home/index.tsx
Call transaction list request periodly
> [ᚬmaster] Update home tx request

- src/pages/Address/AddressComp.tsx
- src/pages/Address/index.tsx
- src/service/app/address.ts
Make `getTipBlockNumber` before of other requests.
> [ᚬmaster] Update address tip block number

- src/components/Search/index.tsx
- Trigger searching event when keyboard done button is pressed
> [ᚬmaster] Update mobile search input event

- .stylelintrc.json
- package.json
- yarn.lock
> [ᚬaggron] Add stylelint

- src/pages/StatisticsChart/mining/DifficultyHashRate.tsx
- src/pages/StatisticsChart/mining/DifficultyUncleRate.tsx
- src/pages/StatisticsChart/mining/UncleRate.tsx
- Update uncle rate chart y-axis max and min value
- Update difficulty chart x-axis format
> Update chart axis max value and format

- src/__tests__/pages/__snapshots__/StatisticCharts.spec.tsx.snap
- src/components/Header/index.tsx
- src/components/Search/index.tsx
- src/locales/en.json
- src/locales/zh.json
- src/pages/StatisticsChart/activities/AddressCount.tsx
- src/pages/StatisticsChart/index.tsx
- src/utils/screen.ts
- Update address count chart title
- Fix screen utils bug
- Update home page search bar focus
> Fix some ui bugs

- src/pages/NervosDao/DaoOverview.tsx
- src/pages/NervosDao/styled.tsx
- Fix Nervos DAO overview address count change error
- Update Nervos DAO pie chart format for mobile
> Fix nervos dao address change and pie format

- src/components/Search/index.tsx
- src/pages/Address/index.tsx
- src/pages/SearchFail/index.tsx
- src/routes/index.tsx
- src/utils/chain.ts
- src/utils/const.ts
- Goto SearchFail page when searched address's chain-type error
- Goto SearchFail page when address URL error
> Refactor processing flow when address's chain type error

- src/__tests__/components/__snapshots__/Script.spec.tsx.snap
- src/pages/Address/index.tsx
- src/pages/NervosDao/index.tsx
- src/service/app/address.ts
- src/utils/const.ts
- src/utils/util.ts
- Distinguish the contract tags between Mainnet and Testnet
- Fetch address txs only when changing page number
- Fetch Nervos DAO txs only when changing page number
> Update some features

- src/constants/scripts.ts
https://github.com/nervosnetwork/rfcs/pull/241/files
> Add cheque cell tags

- src/locales/zh.json
Fix the translation error of 'name_symbol'
> Update zh.json, fixed the translation error of 'name_symbol'

- src/constants/scripts.ts
1. add flashsigner https://github.com/nervina-labs/flash-signer-lock/wiki/Lina-Mainnet-Deployment
2. add cota https://github.com/nervina-labs/ckb-cota-scripts/wiki/Lina-Mainnet-deployment
> feat: add two script tags

- src/components/Search/index.tsx
- src/pages/Address/AddressComp.tsx
- src/pages/Address/styled.tsx
- src/service/http/interceptors.ts
- src/types/index.d.ts
Support NRC 721 with [API](https://github.com/nervosnetwork/ckb-explorer/pull/875)
Ref: https://medium.com/rather-labs/nrc721-nfts-on-nervos-blockchain-d4ad0679c991
> feat: add nrc 721

- src/locales/en.json
- src/locales/zh.json
- src/pages/Address/AddressComp.tsx
- src/pages/Address/styled.tsx
> feat: add unverified nrc 721 display

- src/constants/common.ts
Add NRC 721 related info in token submission template
> feat: update token submission template

- src/constants/common.ts
use ckb-explorer@nervosnet.com instead of asset-info-submit@nervina.io
> feat: update email to submit token info

- src/__tests__/utils/number.test.ts
- src/pages/Address/index.tsx
- src/pages/Home/index.tsx
- src/utils/number.ts
Remove number suffix from epoch number
Before:
After:
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/10
> feat: remove number suffix from epoch number

- src/components/MiranaEasterEgg/index.module.scss
- src/components/MiranaEasterEgg/index.tsx
1. add a link to RFC in countdown
2. adjust layout for mobile
> feat: update easter egg for hardfork

- src/components/Dropdown/ChainType/index.tsx
- src/components/Header/BlockchainComp/index.tsx
- src/components/MiranaEasterEgg/index.module.scss
- src/constants/cache.ts
- src/pages/Home/TableCard/styled.tsx
- src/routes/index.tsx
- src/utils/util.ts
1. rename lina to mirana
2. rename aggron to pudge
3. redirect /aggron to /pudge
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/3
> feat: update chain names on hardfork

- src/constants/common.ts
- src/contexts/states/app.ts
- src/pages/StatisticsChart/activities/AddressBalanceRank.tsx
- src/pages/StatisticsChart/activities/AddressCount.tsx
- src/pages/StatisticsChart/activities/BalanceDistribution.tsx
- src/pages/StatisticsChart/activities/CellCount.tsx
- src/pages/StatisticsChart/activities/OccupiedCapacity.tsx
- src/pages/StatisticsChart/activities/TransactionCount.tsx
- src/pages/StatisticsChart/activities/TxFeeHistory.tsx
- src/pages/StatisticsChart/block/AverageBlockTime.tsx
- src/pages/StatisticsChart/block/BlockTimeDistribution.tsx
- src/pages/StatisticsChart/block/EpochTimeDistribution.tsx
- src/pages/StatisticsChart/mining/Difficulty.tsx
- src/pages/StatisticsChart/mining/DifficultyHashRate.tsx
- src/pages/StatisticsChart/mining/DifficultyUncleRateEpoch.tsx
- src/pages/StatisticsChart/mining/HashRate.tsx
- src/pages/StatisticsChart/mining/MinerAddressDistribution.tsx
- src/pages/StatisticsChart/mining/UncleRate.tsx
- src/pages/StatisticsChart/monetary/AnnualPercentageCompensation.tsx
- src/pages/StatisticsChart/monetary/InflationRate.tsx
- src/pages/StatisticsChart/monetary/Liquidity.tsx
- src/pages/StatisticsChart/monetary/SecondaryIssuance.tsx
- src/pages/StatisticsChart/monetary/TotalSupply.tsx
- src/pages/StatisticsChart/nervosDao/CirculationRatio.tsx
- src/pages/StatisticsChart/nervosDao/NewDaoDeposit.tsx
- src/pages/StatisticsChart/nervosDao/TotalDaoDeposit.tsx
- src/pages/StatisticsChart/network/NewNodeCount.tsx
- src/pages/StatisticsChart/network/NodeDistribution.tsx
Use `useMemo` to cache option, avoid chart duplicate render.
> fix: Avoid duplicate render.

- src/components/MiranaEasterEgg/index.tsx
- src/service/app/statistics.ts
1. fix typo of localStroage methods
2. fix negative left time
> fix: fix countdown of hardfork

- src/pages/BlockDetail/BlockComp.tsx
- src/pages/BlockList/index.tsx
- src/pages/Home/TableCard/index.tsx
1. fix miner address format in block list
2. fix address format in tx list of a block
> fix: fix address format in block info

- src/components/MiranaEasterEgg/index.module.scss
- src/components/MiranaEasterEgg/index.tsx
https://user-images.githubusercontent.com/7271329/167604044-3e4f116f-9ab7-46cb-bb55-e5ab25724e31.mov
> refactor: adjust details of neon text

- src/components/Dropdown/ChainType/index.tsx
- src/components/Header/BlockchainComp/index.tsx
- src/components/Header/MenusComp/index.tsx
- src/config.ts
- src/constants/cache.ts
- src/constants/common.ts
- src/contexts/reducer/app.ts
- src/contexts/states/app.ts
- src/index.tsx
- src/pages/Address/AddressComp.tsx
- src/pages/Home/index.tsx
- src/pages/NervosDao/DaoTransactions/index.tsx
- src/pages/NervosDao/DepositorRank/index.tsx
- src/pages/SearchFail/index.tsx
- src/routes/index.tsx
- src/service/app/statistics.ts
- src/types/index.d.ts
- src/utils/util.ts
1. remove `hasFinishedHardfork`
2. redirect from 'explorer.nervos.org/aggron` or `explorer.nervos.org/pudge` to `pudge.explorer.nervos.org`
> feat: use testnet.baseurl/pathname instead of baseurl/testnet/pathname

- src/components/Card/HashCard/index.tsx
- src/locales/en.json
- src/locales/zh.json
- src/utils/hook.ts
> feat: show link to short address if possible

- package.json
- src/locales/en.json
- src/locales/zh.json
- src/service/http/interceptors.ts
- yarn.lock
Update `axios` to 0.21.4 because of https://github.com/axios/axios/issues/4012
https://user-images.githubusercontent.com/12881040/169756130-4cb10b2a-66aa-4482-a3be-66c0a8e40885.mov
> Adapt too many response

- src/pages/SearchFail/index.tsx
- src/pages/Transaction/TransactionCell/index.tsx
> Deploy to testnet

- src/components/HashTag/index.tsx
- src/constants/scripts.ts
- src/locales/en.json
- src/locales/zh.json
- src/pages/ScriptList/index.tsx
- src/pages/ScriptList/styles.module.scss
- src/routes/index.tsx
1. add a new page to show registered script list
2. add a link from script tag to script list page and expand
the corresponding script
https://user-images.githubusercontent.com/7271329/170077825-2d6d3c15-4c48-4175-8556-a62e83c83c15.mov
> feat: add registered script list

- src/pages/NervosDao/DepositorRank/index.tsx
> fix: set addresses of dao depositors in new format

- .github/workflows/auto_merge_request.yml
add github action to trigger deployment request
> ci: add action to request deployment

- src/utils/hook.ts
Ref: https://github.com/nervosnetwork/ckb-explorer/issues/949
> fix: set is-address-format-new true by default

- src/locales/en.json
- src/locales/zh.json
- src/pages/SimpleUDT/SimpleUDTComp.tsx
- src/pages/SimpleUDT/styles.module.scss
> fix: Always show new address for sudt issuer.

- src/service/app/udt.ts
> fix: Show new address on sudt page.

- package.json
- src/App.tsx
- src/components/Header/MenusComp/index.tsx
- src/components/NftCollectionInventory/index.tsx
- src/components/NftCollectionInventory/styles.module.scss
- src/components/NftCollectionOverview/index.tsx
- src/components/NftCollectionOverview/styles.module.scss
- src/components/NftCollectionTransfers/index.tsx
- src/components/NftCollectionTransfers/styles.module.scss
- src/components/NftHolderList/index.tsx
- src/components/NftHolderList/styles.module.scss
- src/locales/en.json
- src/locales/zh.json
- src/pages/NftCollectionInfo/index.tsx
- src/pages/NftCollectionInfo/styles.module.scss
- src/pages/NftCollections/index.tsx
- src/pages/NftCollections/styles.module.scss
- src/pages/NftInfo/index.tsx
- src/routes/index.tsx
- src/service/http/fetcher.ts
- src/types/index.d.ts
- yarn.lock
1. Nft Collection List
2. Nft Collection Info
1. Transfers
2. Holders
3. Inventory
https://user-images.githubusercontent.com/7271329/177052426-4bd7c5ae-badd-402c-aea4-2bc128509631.mov
> feat: add nft collection info

- src/components/Alert/index.tsx
- src/components/Alert/styles.module.scss
- src/components/Header/styled.tsx
- src/contexts/states/statistics.ts
- src/locales/en.json
- src/locales/zh.json
- src/types/index.d.ts
This commit adds a notification at the top to inform users about occurrence of reorg
Preview:
> feat: add notification of reorg

- .env.production
- public/index.html
1. set ga id configurable
2. use template conditional expression to insert ga script
> feat: update google analytics

- src/components/Alert/index.tsx
- src/locales/en.json
- src/locales/zh.json
The notification will be hidden in 15 minutes since reorg
> feat: add time threshold of displaying reorg notification

- front.conf
> Fix 404 in sub-path

- src/components/Footer/index.tsx
Fix the invalid invite link of discord
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/117
> fix: fix invite link of discord

- .env.develop
- .env.development.example
- .env.production
- .env.production.example
- .gitignore
- README.md
- package.json
- scripts/prepare.js
- yarn.lock
Using .env-cmdrc.js instead .env.*, and provide its example file.
> refactor: env settings

- src/constants/scripts.ts
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/127#issuecomment-1365560897
> feat: add latest deployment info of cota cells

- src/components/TransactionItem/TransactionItemCell/index.module.scss
- src/components/TransactionItem/TransactionItemCell/styled.tsx
- src/pages/Home/TableCard/styled.tsx
fix: some address text overflow
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/152
> fix: some address text overflow

- src/components/TransactionItem/TransactionItemCell/styled.tsx
> fix: layout with transactions list in address page is abnormal

- src/components/Pagination/index.tsx
- src/components/Pagination/styled.tsx
- src/locales/en.json
- src/locales/zh.json
- src/pages/TransactionList/index.tsx
Only the first 5000 pages are accessible for performance
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/119#issuecomment-1370604282
> feat: limit 5000 pages on transaction list page

- src/pages/ScriptList/index.tsx
> fix typo of unipass intro

- src/components/Card/OverviewCard/index.tsx
- src/components/Header/MobileMenu/index.tsx
- src/components/Header/SearchComp/index.tsx
- src/components/Header/index.module.scss
- src/components/Header/index.tsx
- src/components/Search/index.tsx
- src/components/Search/styled.tsx
- src/components/TransactionItem/index.tsx
- src/constants/common.ts
- src/contexts/actions/index.ts
- src/contexts/providers/hook.ts
- src/contexts/reducer/app.ts
- src/contexts/reducer/component.ts
- src/contexts/states/app.ts
- src/contexts/states/components.ts
- src/pages/Address/AddressComp.tsx
- src/pages/Home/AverageBlockTimeChart/index.tsx
- src/pages/Home/HashRateChart/index.tsx
- src/pages/Home/index.module.scss
- src/pages/Home/index.tsx
- src/pages/NervosDao/DaoOverview/index.tsx
- src/pages/StatisticsChart/activities/AddressBalanceRank.tsx
- src/pages/StatisticsChart/common/index.tsx
- src/pages/StatisticsChart/mining/MinerAddressDistribution.tsx
- src/pages/Transaction/TransactionComp.tsx
- src/pages/Transaction/styled.tsx
- src/types/index.d.ts
- src/utils/hook.ts
- src/utils/screen.ts
- src/utils/string.ts
1. Minimize dispatch calls, as this will cause all components that use useAppState to re-render.
1. All the places that listen for changes in window and elements should use hooks to implement re-rendering and should not rely on dispatch to accidentally cause re-rendering.
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/204
> Refactor some nonstandard codes

- src/pages/Home/Banner/render.ts
Reverts nervosnetwork/ckb-explorer-frontend#1208
> Revert "Merge develop into testnet"

- src/locales/en.json
- src/locales/zh.json
- src/pages/404/index.module.scss
- src/pages/404/index.tsx
- src/routes/index.tsx
feat: implement ErrorBoundary for page rendering
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/205
> feat: implement ErrorBoundary for page rendering

- src/components/Footer/index.tsx
- src/components/Header/BlockchainComp/index.tsx
- src/components/Header/LanguageComp/index.tsx
- src/components/Header/MenusComp/index.tsx
- src/components/Header/SearchComp/index.tsx
- src/components/Search/index.tsx
- src/components/Table/index.tsx
- src/components/Text/index.module.scss
- src/components/Text/styled.tsx
- src/pages/Home/AverageBlockTimeChart/index.tsx
- src/pages/Home/Banner/anime.ts
- src/pages/Home/Banner/index.tsx
- src/pages/Home/Banner/render.ts
- src/pages/Home/Banner/renderUtils.ts
- src/pages/Home/HashRateChart/index.tsx
- src/pages/Home/TableCard/index.tsx
- src/pages/Home/index.module.scss
- src/pages/Home/index.tsx
- src/pages/Home/styled.tsx
- src/utils/util.ts
Render time per frame is about 30ms before optimization and 2ms after optimization.
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/175#issuecomment-1434568455
> refactor: improved rendering performance of banner animation

- src/components/Card/HashCard/index.tsx
- src/pages/Address/index.tsx
fix: should always use the ckb address to perform DAS query
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/200
> fix: should always use the ckb address to perform DAS query

- src/pages/Home/HashRateChart/index.tsx
> feat: set label layout of miner hash rate auto

- src/pages/NervosDao/DaoOverview/index.tsx
use data from daily nervos dao statistics to replace the daily changes of nervos dao on nervos dao page
> fix: use a patch on nervos dao page

- src/pages/NervosDao/DaoOverview/index.tsx
feat: set fee rate of 7 days visible
> merge magickbase/develop to nervosnetwork/develop

- package.json
- src/components/NftCollectionTransfers/index.tsx
- src/components/TransactionItem/TransactionLiteItem/index.tsx
- src/components/TransactionItem/index.tsx
- src/pages/Home/TableCard/index.tsx
- src/pages/NftCollectionInfo/index.tsx
- src/utils/date.ts
- src/utils/hook.ts
- yarn.lock
fix: the relative time in some components has not been automatically updated with current time
Considering that there will be opportunities to use RxJS in the future, I have directly imported RxJS in this PR to implement a part of it.
https://user-images.githubusercontent.com/9160743/235109185-d972cd53-37fe-44e8-8193-98a405569cf2.mp4
> fix: the relative time in some components has not been automatically updated with current time

- src/locales/en.json
- src/locales/zh.json
> feat: update maintain i18n

- src/constants/scripts.ts
- src/pages/ScriptList/index.tsx
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/532
> feat: mark force bridge lock

- src/pages/NftCollections/List.tsx
* feat: display non cluster item as Unique items
* refactor: refactor itemName as variable
---------
> feat: display non cluster item as Unique items (#256)

- src/constants/scripts.ts
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/695
Mainnet deployment info: https://github.com/nervosnetwork/rfcs/commit/3078e856461fabe17583ef656b13ac18e5f098dd
Testnet deployment info: https://github.com/nervosnetwork/rfcs/commit/2a1a409a63e16145fbcc878577b5ecb365b97d4d
> feat: update cell info of omnilock v2

- src/constants/scripts.ts
- src/pages/ScriptList/index.tsx
> Add iCKB Scripts info

- src/constants/scripts.ts
- src/pages/ScriptList/index.tsx
- src/pages/Transaction/TransactionCell/index.tsx
ickb script: https://github.com/ickb/proposal#non-upgradable-deployment
ref: https://github.com/nervosnetwork/ckb-explorer-frontend/issues/1784
> feat: add script info of ickb

- src/components/Header/MenusComp/index.module.scss
- src/components/Header/MenusComp/index.tsx
- src/components/Header/MenusComp/styled.tsx
1. add popup for icon link in navigation
2. add icons in navigationfor mobile layout
> feat: refine header

- src/locales/en.json
- src/locales/zh.json
- src/pages/Fiber/GraphNode/LiquidityChart/index.tsx
- src/pages/Fiber/GraphNode/index.module.scss
- src/pages/Fiber/GraphNode/index.tsx
Preview: <img width="1739" alt="image" src="https://github.com/user-attachments/assets/1579d1fe-6448-42d2-a2a1-dc06e1cc49c1" />
> feat: add liquidity allocation on the grpah node page

- jest.setup.js
- package.json
- src/constants/common.ts
- src/pages/NftInfo/index.tsx
- src/utils/spore.ts
- yarn.lock
- Add DOB decoder configuration setup
- Implement automatic config initialization
- Use isMainnet utility for environment detection
- Add getSporeImgFromRenderSDK for DOB image rendering
> feat: integrate DOB render SDK for spore DOBs

- src/pages/Home/Banner/index.tsx
Set the hardfork banner as the first one so all users will see it at the first glance
> feat: highlight the hardfork banner

- src/locales/en.json
- src/locales/zh.json
- src/pages/Fiber/GraphNode/index.module.scss
- src/pages/Fiber/GraphNode/index.tsx
- src/pages/Fiber/GraphNodeList/index.module.scss
- src/pages/Fiber/GraphNodeList/index.tsx
- src/services/ExplorerService/types.ts
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/809#issuecomment-2716703085
Before:
After:
> feat: add last update time on the graph node list and graph node page

- src/pages/Fiber/GraphNode/index.module.scss
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/823#issuecomment-2727278991
> feat: remove colon after label on graph node page

- src/components/TransactionItem/styled.tsx
- src/locales/en.json
- src/locales/zh.json
- src/pages/Script/ScriptsComp.tsx
- src/pages/Script/index.tsx
- src/pages/Script/styles.module.scss
- src/services/ExplorerService/fetcher.ts
* feat: add restrict mode for script transactions
* fix: add restrict params to script url
* chore: optimize ui display
* refactor: use URLSearchParams to join params
---------
> feat: add restrict mode for script transactions (#433)

- src/components/GraphNodeIps/index.tsx
- src/locales/en.json
- src/pages/Fiber/GraphNode/index.tsx
- src/pages/Fiber/GraphNodeList/index.module.scss
- src/pages/Fiber/GraphNodeList/index.tsx
- src/services/UtilityService/index.ts
- src/utils/fiber.tsx
> feat: add isp info of graph node

- src/pages/StatisticsChart/activities/ActiveAddressesChart.tsx
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/832
> feat: add "download data" in active addresses chart

- src/pages/Fiber/GraphNode/index.module.scss
- src/pages/Fiber/GraphNode/index.tsx
- src/pages/Fiber/GraphNodeList/index.module.scss
- src/pages/Fiber/GraphNodeList/index.tsx
ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/843
Before:
After:
> feat: truncate isp name if it's over 20ch

- src/constants/common.ts
- src/hooks/epoch.ts
- src/hooks/halving.ts
- src/hooks/index.ts
- src/pages/HardFork/index.tsx
- src/pages/Home/Banner/Hardfork/index.tsx
update the countdown time dynamically based on the avg. block time
Ref:
1. https://github.com/Magickbase/ckb-explorer-public-issues/issues/817#issuecomment-2893838307
2. https://github.com/Magickbase/ckb-explorer-public-issues/issues/853
> feat: change hardfrok countdown to use real date (#453)

- src/pages/Halving/HalvingCountdown.tsx
- src/pages/Halving/index.module.scss
error in ci: https://github.com/nervosnetwork/ckb-explorer-frontend/actions/runs/15518572151/job/43688717498?pr=1973
> fix: fix typo of digital

- src/pages/HardFork/styles.module.scss
Before and After
1. fix the shrunk 3d cube
2. the border between grid and background is more smooth
> optimize the animation of hardfork

- src/constants/common.ts
- src/locales/en.json
- src/locales/zh.json
Meepo is active after hardfork
> feat: update mainnet alias
