nervosnetwork/ckb-explorer-frontend

- src/pages/BlockDetail/index.tsx
It is the same as the Difficulty display on the home page.
> feat: Add comma to the Difficulty value of the Block page

- src/pages/Transaction/TransactionCell/index.tsx
When the `cell` type is not `cellbase`, the `details` button can be click.
> chore: Fix transaction cell issues

- src/pages/Transaction/TransactionCellArrow/index.tsx
> [ᚬmaster] Update tooltip position

- src/pages/StatisticsChart/BalanceDistribution.tsx
Because of monspace font of aggron explorer, balance distribution chart tooltip width should be set more bigger.
> [ᚬaggron] Update balance distribution tooltip width

- src/components/Modal/index.tsx
- src/pages/Transaction/TransactionCell/index.tsx
The controller of the cell info modal should be uniformly configured outside the component to avoid mutual interference. And the bug is caused by two controllers of inside and outside.
> Fix cell info modal controller bug

- src/service/app/statistics.ts
Data from testnet API are not suitable for hardfork info
> fix: update hardfork info only in mainnet

- src/utils/hook.ts
length of short payload's args is limited to 20bytes according to [RFC](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0021-ckb-address-format/0021-ckb-address-format.md)
before
after
> fix: check args length on transforming into short version address

- src/pages/StatisticsChart/mining/DifficultyHashRate.tsx
- src/pages/StatisticsChart/mining/DifficultyUncleRateEpoch.tsx
- src/service/app/charts/mining.ts
1. show all records instead of truncating the a half
Left: Before, Right: After
2. fix colors of Difficulty & Hash Rate
Left: Before, Right: After
3. adjust chart style of Difficulty & Uncle Rate & Epoch Time & Epoch
Length
Left: Before, Right: After
> feat: update charts related to epochs

- src/pages/StatisticsChart/index.tsx
- src/pages/StatisticsChart/mining/DifficultyHashRate.tsx
- src/pages/StatisticsChart/mining/DifficultyUncleRateEpoch.tsx
- src/routes/index.tsx
- src/service/app/charts/mining.ts
- src/service/http/fetcher.ts
- src/types/index.d.ts
1. Move uncle rate from `Difficulty & Uncle Rate & Epoch Time & Epoch Length` to `Difficulty & Hash Rate`
2. adjust the style of difficulty & hash rate chart and epoch time & epoch length chart, and set initial scale of epoch time & epoch length to the last 1%
> feat: update charts of uncle rate and epoch time/length

- src/constants/scripts.ts
This commit removes an incorrectly recorded sudt script from script list.
The first version of sudt script is of `hash type: data` but it was recorded as of `hash type: type`, which is incorrect.
Besides, the first version of sudt script was never committed into RFCs(there was a draft but closed), so it's not necessary to be listed.
Ref:
- draft PR mentioned the deprecated sudt script: https://github.com/nervosnetwork/rfcs/pull/199
- PR added the incorrect sudt info: https://github.com/nervosnetwork/ckb-explorer-frontend/commit/0b7e28514fb9697e95aeb25c3d221d605a2573be#diff-5636bb1b68c18c68892b6c62dfc3f46f9af26639e920bf49902e70156eedc2a1R156
- discord message: https://discord.com/channels/956765352514183188/959384192859389983/1021428076250407055
> fix: remove deprecated sudt script from script list

- src/pages/Address/AddressComp.tsx
The list was hidden if udt list is empty, but cota list is independent so condition of cota list should be covered too
> fix: fix visibility of udt list of an address

- src/assets/prev_block.svg
- src/locales/en.json
- src/locales/zh.json
- src/pages/BlockDetail/BlockComp.tsx
- src/pages/BlockDetail/styles.module.scss
Add two links to the prev and next blocks, these two links are before and next to the block number on the page
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/71
Preview:
> feat: add links to prev/next block on block page

- src/constants/common.ts
- src/locales/en.json
- src/locales/zh.json
- src/pages/Transaction/TransactionCellScript/index.tsx
- src/pages/Transaction/TransactionCellScript/styled.tsx
This PR adds a `capacity usage` tab in the cell info dialog, the `usage` includes `declared capacity` and `occupied capacity`
1. declared capacity: `capacity` field of the cell
2. occupied capacity: size sum of `capacity` field, `lock` field, `type` field and `data` field
> feat: add capacity usage in cell info

- src/__tests__/utils/string.test.ts
- src/pages/Transaction/TransactionCellScript/index.tsx
- src/utils/string.ts
This PR fixes the incorrect `hexToUtf8` method which cannot handle all utf8 characters before.
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/102#issuecomment-1306604902
> fix: fix hex to utf8 method

- .github/workflows/mainnet.yml
- .github/workflows/staging.yml
- .github/workflows/testnet.yml
Because env vars are difficult to configure in Github, we unified these parameters to secrets.
> Change env vars to secrets

- .github/workflows/_build_deploy.yml
- .github/workflows/mainnet.yml
- .github/workflows/staging.yml
- .github/workflows/testnet.yml
Fix the problem that incorrectly pass `API_URL` to building phase.
Setup 3 different deployment environment in Github:
- staging
- testnet
- mainnet
In these environments, all create a environment secret with the same name `API_URL` with corresponding API URL variable.
> Use environment secrets

- .github/workflows/test.yml
- Dockerfile
The specific version has been changed from 12 to 18 by #1145
1. update node version in github action
2. update node version in docker image
> ci: set node version in ci to 18.12.1

- src/service/app/blockchain.ts
It should be done in the backend, but fixed in front-end temporarily
> fix: filter out the message of deprecating ckb node v0.105

- src/components/Card/OverviewCard/index.tsx
- src/contexts/states/block.ts
- src/contexts/states/transaction.ts
- src/locales/en.json
- src/locales/zh.json
- src/pages/BlockDetail/BlockComp.tsx
- src/pages/Transaction/TransactionComp.tsx
- src/types/index.d.ts
This PR adds the basic `cycles` info on block/transaction pages.
Further details(max cycles in current epoch, max cycles on the chain) will be implemented later
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/87
---
> feat: add basic cycles field on block/transaction pages

- src/components/AddressText/index.tsx
- src/components/Card/HashCard/index.tsx
- src/components/EllipsisMiddle/index.tsx
fix: UI overlap in hash of Address page when going from mobile to non-mobile view
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/172
> fix: UI overlap in hash of Address page when going from mobile to non-mobile view

- src/pages/BlockList/index.tsx
- src/pages/Home/index.tsx
- src/routes/state.ts
- src/service/http/fetcher.ts
Increases the number of requests from 15 to 25 when calling `fetchLatestBlocks` and `fetchLatestTransactions` in the home page, and provide page parameters to trigger the return of meta.
When jumping from the home page to the block list page, the data from the home page will be reused like the transaction list page.
PR based on #1178 .
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/164
> feat: improve ux from home page to list page

- src/pages/Transaction/TransactionCellScript/index.tsx
This PR fixed the page crash by clicking the capacity tab in the cell info dialog. The crash was caused by incorrectly formatted "declared capacity". It was a BigNumber, which is not a valid ReactNode.
Besides, the tab index was reset to 0 when request failed, which made the tab display incorrectly. This issue is also fixed in this PR
Preview:
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/185
> fix: fix page crash on clicking capacity tab in cell info dialog

- src/pages/Address/AddressComp.tsx
- src/types/index.d.ts
fix: address page crashes when address is lockhash
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/200
> fix: address page crashes when address is lockhash

- src/pages/StatisticsChart/common/index.tsx
This PR fixes clicking on address rank by setting the rank data on fetching
The data set(https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/pages/StatisticsChart/activities/AddressBalanceRank.tsx#L115-L117) used in onclick handler is expected to be data of the chart, but it's not updated by `onFetch` as expected because `onFetch` is not called when the data are fetched from cache or network
> fix: fix clicking on address rank

- src/pages/StatisticsChart/activities/AddressBalanceRank.tsx
navigate back to `address-balance-rank` chart page, but 404 page is arrived at.
https://github.com/Magickbase/ckb-explorer-public-issues/issues/211
> fix: incorrect page navigation 404

- src/pages/StatisticsChart/nervosDao/TotalDaoDeposit.tsx
> fix: Label in `Total Nervos DAO Deposit` chart is overlapped

- src/pages/FeeRateTracker/FeeRateTrackerComp.tsx
It is a grouping issue of `feeRates/confirmationTime`
I divided data into a left open right close range.
The label of x-axis and tooltip needs some suggestion? Is it necessary to show that's a left open right close range @Keith-CY
> fix: divided `feeRates/confirmationTime` into a left open right close range

- src/pages/Home/Banner/index.tsx
Fallback banner to static image on mainnet due to performance issue of animated banner
> feat: fallback banner to static image on mainnet

- src/components/Script/index.tsx
- src/constants/scripts.ts
- src/pages/ScriptList/index.tsx
- src/pages/Transaction/TransactionCellScript/index.tsx
- src/utils/util.ts
Issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/274
> fix: show `locktime` script tag in `multisig` script only when script args length is 28bytes

- src/__tests__/utils/string.test.ts
- src/pages/Address/index.tsx
- src/utils/hook.ts
- src/utils/string.ts
The default page sizes of transaction list on the account page are inconsistent in query and pagination component
`usePaginationParamsInPage` was used in the query while `usePaginationParamsInListPage` was used in the pagination component
> fix: fix default page size of transactions on the account page

- src/components/Alert/index.tsx
- src/constants/common.ts
This commit allows the maintenance info to be displayed by setting an environment variable "REACT_APP_IS_MAINTAINING=true" So Devops can toggle the maintenance status by restarting the service with different runtime env
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/397
> chore: show maintenance info

- src/pages/StatisticsChart/common/index.tsx
According to the hook rule, we cannot call hooks in a primitive hook, such as `useMemo`, `useReducer`, or `useEffect`, and there are several [getEChartOption](https://github.com/nervosnetwork/ckb-explorer-frontend/blob/272c55939f7e5f295e87255806b89d34bba15172/src/pages/StatisticsChart/activities/AddressBalanceRank.tsx#L136)s are wrapped with `useCallback`
> fix: cannot call hooks in useMemo

- _typos.toml
because several hashes are included in tests
> ci: exclude checking typos in tests

- jest.setup.js
- package.json
- src/constants/common.ts
- src/models/Address/UDTAccount.ts
- src/pages/Address/AddressAssetComp.tsx
- src/pages/NftCollectionInfo/ItemCover/index.tsx
- src/pages/NftCollectionInfo/ItemCover/styles.module.scss
- src/pages/NftCollectionInfo/NftCollectionInventory/index.tsx
- src/pages/NftCollectionInfo/NftCollectionInventory/styles.module.scss
- src/pages/NftCollectionInfo/NftCollectionTransfers/index.tsx
- src/pages/NftCollectionInfo/NftCollectionTransfers/styles.module.scss
- src/pages/NftInfo/Cover/index.tsx
- src/pages/NftInfo/Cover/styles.module.scss
- src/pages/NftInfo/index.tsx
- src/pages/NftInfo/styles.module.scss
- src/utils/spore.ts
- yarn.lock
This pull request introduces several changes to integrate and utilize the `@nervina-labs/dob-render` package for rendering images. The changes include mocking the package for tests, updating dependencies, and refactoring multiple components to use the new image rendering logic.
* [`jest.setup.js`](diffhunk://#diff-4c3cfde2c8298e64ca709feb98ce653c1f25d523dc113f5fc097d9314ec785efR4-R13): Mocked the `@nervina-labs/dob-render` package for testing purposes.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17): Added `@nervina-labs/dob-render` as a dependency and updated Jest configuration to handle the new package. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17) …
> refactor: use spore sdk to fetch spore image

- src/pages/Address/AddressAssetComp.tsx
- src/pages/NftInfo/NameMissing.svg
- src/pages/NftInfo/index.tsx
- src/pages/NftInfo/styles.module.scss
- Update address page NFT links to point directly to detail pages instead of collection pages
- Add collection link on NFT detail page for better navigation
Before:
https://github.com/user-attachments/assets/92c6c823-8782-40d4-943b-169af9240a87
After: 
https://github.com/user-attachments/assets/74c643f3-0750-402a-a22f-a5d6063f86ff
> feat: improve NFT navigation links

- src/pages/Fiber/GraphNodeList/index.tsx
- src/styles/table.module.scss
block hover event propagation when hidden threshold is hovered
Before
After
> feat: optimize hover effect on graph node list page

- src/components/HelpTip/index.module.scss
- src/locales/en.json
- src/locales/zh.json
- src/pages/Transaction/TransactionComp/TransactionOverview.tsx
Display "untracked" when the transaction is not found in tx pool instead of displaying "pending" as a fallback
Before
After
> fix: fix tx status when it's not found

- src/pages/Fiber/GraphNode/index.tsx
- src/pages/Fiber/GraphNodeList/index.tsx
- src/services/ExplorerService/types.ts
Use `created timestamp` as the first seen time because the default timestamp will be refreshed when the node broadcasts its info
> feat: use created_timestamp as the first seen time

- src/pages/Fiber/Graph/index.tsx
display formatted number instead of raw number
Before
After
> feat: optimize display of total capacity diff

- src/__tests__/pages/Fiber/Graph/utils.test.ts
- src/pages/Fiber/Graph/HistoryChart/index.tsx
- src/pages/Fiber/Graph/index.tsx
- src/pages/Fiber/Graph/types.ts
- src/pages/Fiber/Graph/utils.ts
- src/pages/Fiber/GraphNode/index.tsx
- src/services/ExplorerService/types.ts
- src/services/UtilityService/index.ts
use total USD liquidity instead of total capacity of CKB
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/838#issuecomment-2774311686
Before:
After:
> feat: update total liquidity of fiber graph

- src/pages/Home/index.module.scss
- src/pages/Home/index.tsx
> fix: fix font size in the chart on the homepage

- src/components/HashTag/index.tsx
> fix: hide hashtag if tag is empty
